name: ci/cd front

on:
  workflow_dispatch:

  push:
    branches: [main]

env:
  REACT_APP_BACK_URL : https://backend-is3-production.up.railway.app


jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node 19
        uses: actions/setup-node@v1
        with:
          node-version: 19.x

      - name: Install packages
        working-directory: ./FrontEnd
        run: npm i 
        
      - name: Run Test
        working-directory: ./FrontEnd
        run: npm run test

  build-docker-image:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: '${{ secrets.DOCKER_USER }}'
          password: '${{ secrets.DOCKER_PSW }}'

      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: FrontEnd/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/frontend-is3:${{ github.run_number }}

  deploy-to-railway:
    runs-on: ubuntu-latest
    needs: build-docker-image
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node 19
        uses: actions/setup-node@v1
        with:
          node-version: 19.x

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up -s frontend-is3 
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

  integration-test:
    runs-on: ubuntu-latest
    needs: deploy-to-railway
    steps:
      - name: Get Integration Test Repository
        uses: actions/checkout@v3
        with:
          repository: AngeloMenel98/ing3-integrador
          path: ing3-integrador

      - name: Use Node 19
        uses: actions/setup-node@v1
        with:
          node-version: 19.x

      - name: Install packages
        working-directory: ./ing3-integrador
        run: npm ci

      - name: Run Integration Test and Report
        working-directory: ./ing3-integrador
        run: TESTOMATIO=${{secrets.TESTTOMAT_API_KEY}} npx codeceptjs run
